name: Generate 10x Disruption Posts

on:
  schedule:
    # JST：0時 / 2時 / 4時 / 6時 / 8時 / 10時 / 12時 / 14時 / 16時 / 18時
    - cron: "0 15,17,19,21,23,1,3,5,7,9 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install openai

      - name: Run Disruption Generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python generate_disruption_posts.py

      - name: Commit and push (optional, if saving)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto: generate 10x disruption posts" || echo "No changes"
          git push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
