name: Generate Monthly CDI ZINE

on:
  schedule:
    - cron: '0 0 1 * *'  # 毎月1日 00:00 UTC（JST 09:00）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --upgrade pip

      - name: Run ZINE monthly summary
        run: |
          python generate_monthly_zine_cdi.py

      - name: Commit and push monthly ZINE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add zine_monthly/
          git diff --cached --quiet && echo "No changes to commit." || (
            git commit -m "Auto: generated monthly CDI ZINE"
            git push
          )
